import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'doc', id: 'getting-started/chapter-1-introduction-to-physical-ai'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      link: {type: 'doc', id: 'module-1-ros2/week-3-ros2-foundations/chapter-6-ros2-architecture-and-core-concepts'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'module-1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      link: {
        type: 'doc',
        id: 'module-2-digital-twin/week-6-gazebo-simulation/chapter-15-introduction-to-robot-simulation', // Links to the first chapter of week 6
      },
      collapsed: true, // Set to false if you want it expanded by default
      items: [
        {
          type: 'category',
          label: 'Week 6: Gazebo Simulation',
          link: {
            type: 'doc',
            id: 'module-2-digital-twin/week-6-gazebo-simulation/chapter-15-introduction-to-robot-simulation', // Optional: link to the first doc of this sub-category
          },
          items: [{ type: 'autogenerated', dirName: 'module-2-digital-twin/week-6-gazebo-simulation' }],
        },
        {
          type: 'category',
          label: 'Week 7: Advanced Simulation',
          link: {
            type: 'doc',
            id: 'module-2-digital-twin/week-7-advanced-simulation/chapter-20-unity-for-high-fidelity-rendering', // Links to the first chapter of Week 7
          },
          items: [{ type: 'autogenerated', dirName: 'module-2-digital-twin/week-7-advanced-simulation' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      link: {type: 'doc', id: 'module-3-isaac/week-8-isaac-platform-introduction/chapter-23-nvidia-isaac-platform-overview'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'module-3-isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {type: 'doc', id: 'module-4-vla/week-11-humanoid-development/chapter-34-humanoid-robot-kinematics-and-dynamics'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'module-4-vla'}],
    },
    {
      type: 'category',
      label: 'Hardware & Lab Setup',
      link: {type: 'doc', id: 'hardware/chapter-46-understanding-hardware-requirements'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'hardware'}],
    },
    {
      type: 'category',
      label: 'Capstone Project: The Autonomous Humanoid',
      link: {type: 'doc', id: 'capstone/chapter-51-capstone-project-overview'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'capstone'}],
    },
    {
      type: 'category',
      label: 'Resources',
      link: {type: 'doc', id: 'resources/glossary-of-terms'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'resources'}],
    },
  ],
};

export default sidebars;
